# Generated by Django 4.1.1 on 2022-10-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerceapp', '0004_order_tags_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='commerceapp.tag'),
        ),
    ]
