# Generated by Django 4.1.1 on 2022-10-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerceapp', '0006_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
