# Generated by Django 4.1.1 on 2022-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerceapp', '0008_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
